#feign:
#  client:
#    config:
#      products:
#        connectTimeout: 5000
#        readTimeout: 5000
#        loggerLevel: FULL

spring:
  cassandra:
    keyspace-name: rjcassandra
    contact-points: 127.0.0.1
    port: 9042
    localDatacenter: datacenter1

server:
  error:
    include-message: always


logging:
  level:
    org:
      springframework: INFO
    com:
      example:
        springhub:
          kafka: DEBUG

management:
  endpoint:
    health:
      show-details: always